### PR TITLE
Update to use portFromEnv and newest proxy

### PR DESCRIPTION
**Pull request by zionts**
- Adds portFromEnv and thus removes extra step of writing from env -> config
- Sets up support for persisted queries
- Bumps version

### CODE REVIEW

**Comment by thepwagner** [comment]
Since you're not doing much shell-y any more, you can boil the Dockerfile down to:
``` FROM gcr.io/engine:someversion
COPY config.json /config.json
ENTRYPOINT ["/engineproxy_linux_amd64","-config","/config.json" ]
```

Builds would be faster (less copying) and pushes a little bit too (shaves a few MB)

**Comment by zionts** [comment]
@thepwagner would we still have to copy over the binary?

**Comment by thepwagner** [comment]
Nope; you'd be starting `FROM` the image with the binary already in place.

**Comment by timbotnik** [comment]
This is cool!  @zionts now that we have the `portFromEnv` option, another way to go about this is to just pass the entire Engine config down through the environment variables in Heroku - then you don't need to even build a wrapper container but merely tag / deploy the base image from Engine.  LMK if you want to talk about that solution.  There is one downside which is that the JSON formatting is a bit tricky to get right; the Heroku env var interface in their admin panel does strange things to newlines.  That said, I think the instructions you have here ^^ should be the recommended way to use Engine, as it is easier to handle the config and gives you a jumping off point should you want to customize the image at all.

**Pull request merged**
